#ifndef _H_MODULE_ID_
#define _H_MODULE_ID_

// START AUTOGENERATED CODE from Excel Sheet on 14:05:51 12.03.2014
// Source File C:\Users\Aiko\Dropbox\Studiprojekt\Documents\Documents\[GlobalDefines.xlsx]General
typedef enum
{
    MODULE_ID_NO               = 0x0000, // No Module
    MODULE_ID_MUX              = 0x0001, // Interface to the LED Module
    MODULE_ID_COM              = 0x0002, // Communication Handler for the UDP Communication
    MODULE_ID_GUI              = 0x0004, // The Graphical Interface
    MODULE_ID_GMM              = 0x0008, // Displays a streamed picture
    MODULE_ID_STREAM           = 0x0010, // Displays a streamed picture
    MODULE_ID_BARS             = 0x0020, // Dispays running bars
    MODULE_ID_MONO             = 0x0040, // Displays a monochrome color.
    MODULE_ID_PLASMA           = 0x0080, // Displays plasma like movement
    MODULE_ID_SNAKE            = 0x0100, // Snake game
    MODULE_ID_PHOTO            = 0x0200, // Displays images on the led wall
    MODULE_ID_BALL             = 0x0400  // Moving Balls
} module_id_t, *p_module_id_t; 
// END OF AUTOGENERATED CODE

#endif //_H_MODULE_ID_
