#ifndef _H_CLIENT_TYPE_
#define _H_CLIENT_TYPE_

// START AUTOGENERATED CODE from Excel Sheet on 18:08:05 13.11.2013
// Source File D:\Dropbox\Studiprojekt\Documents\Communication\[Communication.xlsx]FC Details
typedef enum
{
    CLIENT_ANDROID_APP         = 0x01, // Android App
    CLIENT_WEBSITE             = 0x02, // The website / server
    CLIENT_WINDOWS_APP         = 0x04  // Windows application
} client_type_t, *p_client_type_t; 
// END OF AUTOGENERATED CODE

#endif //_H_CLIENT_TYPE_
