#ifndef _H_ERROR_
#define _H_ERROR_

// START AUTOGENERATED CODE from Excel Sheet on 17:40:07 19.11.2013
// Source File C:\Users\Aiko\Dropbox\Studiprojekt\Documents\Communication\[Communication.xlsx]ErrCodes
typedef enum
{
    ERR_CODES_OK                              = 0x00, // Ok
    ERR_CODES_NOK                             = 0x01, // Not Ok
    ERR_CODES_VERSION                         = 0x02, // Incompatible Versions
    ERR_CODES_UNEXPECTED_PAYLOAD              = 0x03, // Unexpected payload
    ERR_CODES_GMODULE                         = 0x03, // GModule could not be activated
    ERR_CODES_GMODULE_NA                      = 0x04  // GModule does not exist
} error_code_t, p_err_code_t; 
// END OF AUTOGENERATED CODE

#endif //_H_ERROR_
