#include "net/messages.h"

// START AUTOGENERATED CODE from Excel Sheet on 15:34:48 13.03.2014
// Source File C:\Users\Aiko\Dropbox\Studiprojekt\Documents\Communication\[Communication.xlsx]FC
const interpreter_t tblInterpreter[] = 
// FC, MIN, MAX, FUNC
{
    /* 0x0001 */ {      3,      3, MsgHandlerHandshake                     }, // Msg: HANDSHAKE
    /* 0x0002 */ {      0,      0, MsgHandlerVersionInfo                   }, // Msg: VERSION_INFO
    /* 0x0003 */ {      0,      2, gmm_change                              }, // Msg: GMODULE
    /* 0x0004 */ {      0,      7, mono_mono                               }, // Msg: MONO_MONO
    /* 0x0005 */ {      1,      1, MsgSnake_Start                          }, // Msg: SNAKE_START
    /* 0x0006 */ {      1,      1, MsgSnake_Direction                      }, // Msg: SNAKE_DIRECTION
    /* 0x0007 */ {      2,      2, MsgPhoto_Change                         }, // Msg: PHOTO_CHANGE
    /* 0x0008 */ {      0,     29, MsgBalls_Change                         }, // Msg: BALLS_CHANGE
    /* 0x0009 */ {      0,      2, MsgPlasma_Change                        }  // Msg: PLASMA_CHANGE
}; 
// END OF AUTOGENERATED CODE

uint16_t interpreterCount = sizeof(tblInterpreter) / sizeof(tblInterpreter[0]);
